// чтобы удалить пустые строки нужно ввести в CTRL+F или CTRL R
// ^\s*$\n
const questionsData = {


  testQuicklyData: [
    { id: 1, eng: "What is the capital of Great Britain?", ru: "Какая столица Великобритании?"},
    { id: 2, eng: "What is the capital of USA?", ru: "Какая столица Америки?"},


  ],
  introLessonQuestionsSmallTalk1: [
    { id: 1, eng: "What city are you from?", ru: "Из какого вы города? - I am from New-York"},
    { id: 2, eng: "What is your father's name?", ru: "Как зовут вашего отца? - My father's name is Andrew"},
    { id: 4, eng: "What is your favorite color?", ru: "Какой твой любимый цвет? - My favorite color is blue."},
    { id: 5, eng: "How old are you?", ru: "Сколько тебе лет? - I am always 18"},
    { id: 6, eng: "Do you have brothers or sisters?", ru: "У тебя есть братья или сестры? - I (don't) have" },
    { id: 7, eng: "Do you like cats or dogs more?", ru: "Ты больше любишь кошек или собак? - I like dogs more."},
    { id: 8, eng: "What is your job?", ru: "Какая твоя работа? - I help people practice English."},
    { id: 9, eng: "What is your favorite months of the year?", ru: "Какой твой любимый месяц в году? - I think February, cuz ..." },
    { id: 10, eng: "What is your favorite drink?", ru: "Какой твой любимый напиток? - I think water or vodka with orange juice, because I am an alcoholic! (It's a joke)" },
    { id: 11, eng: "What time is it on your clock now?", ru: "Сколько сейчас времени у тебя на часах? - It is 20:12 now /твЭнти твЭлв/ 8:12 pm"},
    { id: 12, eng: "How is the weather today?", ru: "Какая сегодня погода? - It is (not) very cold / hot today, about 15 degrees (below zero)"},
    { id: 13, eng: "What films do you like to watch?", ru: "Какие фильмы ты любишь смотреть? - I like comedies / action / fantasy / historical / animations / anime"},
    { id: 14, eng: "What did you do yesterday?", ru: "Что ты делал вчера? - I worked and met my friends and we went to a bar yesterday."}
  ],
  ForgettingCurveB1: [
    { id: 1, eng: "The faster a man drives a car, the more risk he has", ru: "Чем быстрее мужчина водит машину, тем больше у него риска" },
    { id: 2, eng: "The tastier a woman cooks, the happier her husband is", ru: "Чем вкуснее готовит женщина, тем счастливее ее муж" },
    { id: 3, eng: "The less oil costs, the more gasoline costs", ru: "Чем меньше стоит нефть, тем больше стоит бензин" },
    { id: 4, eng: "The cheaper the price is, the lower the quality is", ru: "Чем дешевле цена, тем ниже качество" },
    { id: 5, eng: "The stronger a person is, the more stupid he is", ru: "Чем сильнее человек, тем он глупее" },
    { id: 6, eng: "The more confident I become, the more I enjoy speaking.", ru: "Чем увереннее я становлюсь, тем больше мне нравится говорить." },
    { id: 7, eng: "The harder the grammar, the cooler you are when you use it", ru: "Чем сложнее грамматика, тем ты круче, когда используешь ее" },
    { id: 8, eng: "The more focused I am, the faster I learn.", ru: "Чем больше я сосредоточен, тем быстрее я учусь." },
    { id: 9, eng: "The sooner we start, the sooner we finish.", ru: "Чем раньше мы начнем, тем раньше мы закончим." },
    { id: 10, eng: "The earlier you wake up, the angrier you are", ru: "Чем раньше ты просыпаешься, тем злее ты" },
    { id: 11, eng: "The more interesting the topic is, the easier it is to remember.", ru: "Чем интереснее тема, тем легче ее запомнить." },
    { id: 12, eng: "The more I listen to English, the better my pronunciation improves", ru: "Чем больше я слушаю английский, тем лучше становится мое произношение" },
    { id: 13, eng: "The better my pronunciation is, the more people understand me.", ru: "Чем лучше мое произношение, тем больше люди меня понимают." },
    { id: 14, eng: "The more words I know, the more detailed I can describe my thoughts.", ru: "Чем больше слов я знаю, тем подробнее я могу описать свои мысли." },
    { id: 15, eng: "The more I challenge myself, the faster I progress.", ru: "Чем больше я бросаю себе вызов, тем быстрее я прогрессирую." },
    { id: 16, eng: "The more Vincent knows me, the more he likes me.", ru: "Чем больше Винсент узнает меня, тем больше я ему нравлюсь." },
    { id: 17, eng: "The more I review, the less I forget", ru: "Чем больше я повторяю, тем меньше я забываю" },
    { id: 18, eng: "The less I review, the more I forget", ru: "Чем меньше я повторяю, тем больше я забываю" },
    { id: 19, eng: "The more I forget, the less I know", ru: "Чем больше я забываю, тем меньше я знаю" },
    { id: 20, eng: "The less you know, the better you sleep", ru: "Чем меньше ты знаешь, тем лучше ты спишь" },
    { id: 21, eng: "The better I sleep, the more energetic I am", ru: "Чем лучше я сплю, тем я энергичнее" },
    { id: 22, eng: "The faster I read, the faster I speak", ru: "Чем быстрее я читаю, тем быстрее я говорю" },
    { id: 23, eng: "The slower I read, the more Vincent wants to sleep", ru: "Чем медленнее я читаю, тем больше Винсент хочет спать" },
    { id: 24, eng: "The more I repeat, the faster I speak", ru: "Чем больше я повторяю, тем быстрее я говорю" },
    { id: 25, eng: "The faster I speak, the more interesting it is.", ru: "Чем быстрее я говорю, тем интереснее." },
    { id: 26, eng: "The more mistakes I make, the more experience I have", ru: "Чем больше ошибок я делаю, тем больше у меня опыта" },
    { id: 27, eng: "The more experience I have, the more stories I can tell", ru: "Чем больше у меня опыта, тем больше историй я могу рассказать" }
  ],
    introSetAlias: [
      // Цвета
      { id: 1, eng: "red", ru: "красный", hint: "/ рэд /" },
      { id: 2, eng: "blue", ru: "синий", hint: "/ блу /" },
      { id: 3, eng: "green", ru: "зелёный", hint: "/ грин /" },
      { id: 4, eng: "yellow", ru: "жёлтый", hint: "/ йЕлоу /" },
      { id: 5, eng: "black", ru: "чёрный", hint: "/ блэк /" },
      { id: 6, eng: "white", ru: "белый", hint: "/ уайт /" },
      { id: 7, eng: "brown", ru: "коричневый", hint: "/ браун /" },
      { id: 8, eng: "orange", ru: "оранжевый", hint: "/ Ориндж /" },
      { id: 9, eng: "pink", ru: "розовый", hint: "/ пинк /" },
      { id: 10, eng: "gray", ru: "серый", hint: "/ грэй /" },

      // Животные
      { id: 11, eng: "cat", ru: "кот", hint: "/ кэт /" },
      { id: 12, eng: "dog", ru: "собака", hint: "/ дог /" },
      { id: 13, eng: "cow", ru: "корова", hint: "/ кау /" },
      { id: 14, eng: "duck", ru: "утка", hint: "/ дак /" },
      { id: 15, eng: "pig", ru: "свинья", hint: "/ пиг /" },
      { id: 16, eng: "horse", ru: "лошадь", hint: "/ хoрс /" },
      { id: 17, eng: "fish", ru: "рыба", hint: "/ фиш /" },
      { id: 18, eng: "bird", ru: "птица", hint: "/ бёрд /" },
      { id: 19, eng: "rabbit", ru: "кролик", hint: "/ рэбит /" },
      { id: 20, eng: "bear", ru: "медведь", hint: "/ бэа /" },

      // Транспорт
      { id: 21, eng: "car", ru: "машина", hint: "/ кар /" },
      { id: 22, eng: "bus", ru: "автобус", hint: "/ бас /" },
      { id: 23, eng: "bicycle", ru: "велосипед", hint: "/ байсикл /" },
      { id: 24, eng: "train", ru: "поезд", hint: "/ трейн /" },
      { id: 25, eng: "plane", ru: "самолёт", hint: "/ плейн /" },
      { id: 26, eng: "ship", ru: "корабль", hint: "/ шип /" },

      // Профессии
      { id: 27, eng: "doctor", ru: "врач", hint: "/ доктэ /" },
      { id: 28, eng: "professor", ru: "профессор", hint: "/ профЭссор /" },
      { id: 29, eng: "driver", ru: "водитель", hint: "/ драйвэ /" },
      { id: 30, eng: "police", ru: "полиция", hint: "/ полИс /" },
      { id: 31, eng: "student", ru: "студент", hint: "/ стьЮдэнт /" },

      // Еда
      { id: 32, eng: "pineapple", ru: "ананас", hint: "/ пайн эпл /" },
      { id: 33, eng: "banana", ru: "банан", hint: "/ бэ'нана /" },
      { id: 34, eng: "carrot", ru: "морковь", hint: "/ кэрэт /" },
      { id: 35, eng: "bread", ru: "хлеб", hint: "/ бред /" },
      { id: 36, eng: "milk", ru: "молоко", hint: "/ милк /" },
      { id: 37, eng: "cheese", ru: "сыр", hint: "/ чиз /" },
      { id: 38, eng: "eggs", ru: "яйца", hint: "/ эгз /" },
      { id: 38, eng: "pizza", ru: "пицца", hint: "/ пицца /" },

      { id: 39, eng: "cucumber", ru: "огурец", hint: "/ кьЮкамбэ /" },

      // Школьные принадлежности
      { id: 40, eng: "book", ru: "книга", hint: "/ бук /" },
      { id: 41, eng: "pen", ru: "ручка", hint: "/ пэн /" },
      { id: 42, eng: "pencil", ru: "карандаш", hint: "/ пэнсил /" },
      { id: 43, eng: "bag", ru: "сумка", hint: "/ бэг /" },
      { id: 44, eng: "ruler", ru: "линейка", hint: "/ рулэ /" },
      { id: 45, eng: "eraser", ru: "ластик", hint: "/ ирэйзэ /" },
      { id: 46, eng: "notebook", ru: "тетрадь", hint: "/ ноутбук /" },
      { id: 47, eng: "chair", ru: "стул", hint: "/ чэа /" },
      { id: 47, eng: "phone", ru: "телефон", hint: "/ фОун /" },
      { id: 47, eng: "Android", ru: "андроид", hint: "/ Эндроид /" },

      // Прилагательные (внешность)
      { id: 48, eng: "beautiful", ru: "красивая" },
      { id: 49, eng: "handsome", ru: "красивый" },
      { id: 50, eng: "tall", ru: "высокий" },
      { id: 51, eng: "short", ru: "низкий" },
      { id: 52, eng: "hungry", ru: "голодный" },
      { id: 52, eng: "angry", ru: "злой" },
      { id: 52, eng: "disgusting", ru: "отвратительный" },

      // Части тела
      { id: 53, eng: "head", ru: "голова" },
      { id: 54, eng: "nose", ru: "нос" },
      { id: 55, eng: "eyes", ru: "глаза" },
      { id: 56, eng: "fingers", ru: "пальцы" },
      { id: 56, eng: "shoulders", ru: "плечи" },
      { id: 56, eng: "lips", ru: "губы" },
      { id: 56, eng: "legs", ru: "ноги" },
      { id: 56, eng: "hands", ru: "кисти рук" },

      // Дни недели
      { id: 57, eng: "Monday", ru: "понедельник", hint: "/ мАндэй /" },
      { id: 58, eng: "Tuesday", ru: "вторник", hint: "/ тьЮздэй /" },
      { id: 59, eng: "Wednesday", ru: "среда", hint: "/ уЭнздэй /" },
      { id: 60, eng: "Thursday", ru: "четверг", hint: "/ THЁздэй /" },
      { id: 61, eng: "Friday", ru: "пятница", hint: "/ фрАйдэй /" },
      { id: 62, eng: "Saturday", ru: "суббота", hint: "/ сАтэдэй /" },
      { id: 63, eng: "Sunday", ru: "воскресенье", hint: "/ сАндэй /" },

      // Месяцы
      { id: 64, eng: "January", ru: "январь", hint: "/ джЭньюэри /" },
      { id: 65, eng: "February", ru: "февраль", hint: "/ фЭбруэри /" },
      { id: 66, eng: "March", ru: "март", hint: "/ марч /" },
      { id: 67, eng: "April", ru: "апрель", hint: "/ Эйприл /" },
      { id: 68, eng: "May", ru: "май", hint: "/ мэй /" },
      { id: 69, eng: "June", ru: "июнь", hint: "/ джун /" },
      { id: 70, eng: "July", ru: "июль", hint: "/ джуЛай /" },
      { id: 71, eng: "August", ru: "август", hint: "/ Огэст /" },
      { id: 72, eng: "September", ru: "сентябрь", hint: "/ сэптЭмбэ /" },
      { id: 73, eng: "October", ru: "октябрь", hint: "/ октОубэ /" },
      { id: 74, eng: "November", ru: "ноябрь", hint: "/ новЭмбэ /" },
      { id: 75, eng: "December", ru: "декабрь", hint: "/ дисЭмбэ /" },

      { id: 76, eng: "Cigarette", ru: "сигарета"},
      { id: 76, eng: "Electric scooter", ru: "электросамокат"},
      { id: 76, eng: "Internet", ru: "интернет"},
      { id: 76, eng: "Vincent", ru: "вИнсент"},

    ],

  who1: [

      { id: 1, eng: "irons clothes", ru: "гладит одежду" },
      { id: 2, eng: "walks with a dog", ru: "гуляет с собакой" },
      { id: 3, eng: "works", ru: "работает" },
      { id: 4, eng: "picks flowers", ru: "собирает цветы" },
      { id: 5, eng: "kills mosquitoes", ru: "убивает комаров" },
      { id: 6, eng: "studies English", ru: "учит английский" },
      { id: 7, eng: "washes dirty socks", ru: "стирает грязные носки" },
      { id: 8, eng: "sweeps the floor", ru: "подметает полы" },
      { id: 9, eng: "washes the dishes", ru: "моет посуду" },
      { id: 10, eng: "cleans the house", ru: "убирает дом" },
      { id: 11, eng: "cooks food", ru: "готовит еду" },
      { id: 12, eng: "bakes cakes", ru: "печёт торты" },
      { id: 13, eng: "fixes broken things", ru: "чинит сломанные вещи" },
      { id: 14, eng: "goes shopping", ru: "ходит в магазин" },
      { id: 15, eng: "changes the bedsheets", ru: "меняет постельное бельё" },
      { id: 16, eng: "makes the bed", ru: "заправляет постель" },
      { id: 17, eng: "vacuums", ru: "пылесосит" },
      { id: 18, eng: "does English homework", ru: "делает домашку по английскому" },
      { id: 19, eng: "takes out the trash", ru: "выносит мусор" },
      { id: 20, eng: "spends money", ru: "тратит деньги" },
      { id: 21, eng: "reads books", ru: "читает книги" },
      { id: 22, eng: "watches TikTok", ru: "смотрит тикток" },
      { id: 23, eng: "plays computer games", ru: "играет в компьютерные игры" },
      { id: 24, eng: "goes to the gym", ru: "ходит в спортзал" },
      { id: 25, eng: "draws beautifully", ru: "рисует красиво" },
      { id: 26, eng: "sleeps all day", ru: "спит весь день" },
      { id: 27, eng: "does nothing all day", ru: "ничего не делает весь день" }

  ],

  whoAnswers1:
[
  { id: 1, eng: "I", ru: "Я" },
  { id: 2, eng: "you", ru: "ты / вы" },
  { id: 3, eng: "everybody", ru: "все" },
  { id: 4, eng: "all my friends", ru: "все мои друзья" },
  { id: 5, eng: "all my family", ru: "вся моя семья" },
  { id: 6, eng: "nobody", ru: "никто" },
  { id: 7, eng: "my neighbour", ru: "мой сосед / соседка" },
  { id: 8, eng: "my best friend", ru: "мой лучший друг / подруга" },
  { id: 9, eng: "my teacher of English", ru: "мой учитель английского" },
  { id: 10, eng: "Vincent", ru: "Винсент" },
  { id: 11, eng: "my boyfriend", ru: "мой парень" },
  { id: 12, eng: "my dog", ru: "моя собака" },
  { id: 13, eng: "my boss", ru: "мой начальник" },
  { id: 14, eng: "I don't know who", ru: "я не знаю кто" },
  { id: 15, eng: "my grandmother", ru: "моя бабушка" },
  { id: 16, eng: "my uncle", ru: "мой дядя" },
  { id: 17, eng: "my mom", ru: "моя мама" },
  { id: 18, eng: "my dad", ru: "мой папа" },
  { id: 19, eng: "I don't remember who", ru: "я не помню кто" },
  { id: 20, eng: "my older child", ru: "мой старший ребёнок" }
],

  whatISitVideoMission: [
    { id: 1, eng: "a list", ru: "список", hint: "/ə lɪst/" },
    { id: 2, eng: "a phone", ru: "телефон", hint: "/ə fəʊn/" },
    { id: 3, eng: "headphones", ru: "наушники", hint: "/ˈhɛdfəʊnz/" },
    { id: 4, eng: "a pen", ru: "ручка", hint: "/ə pɛn/" },
    { id: 5, eng: "a pencil", ru: "карандаш", hint: "/ə ˈpɛnsəl/" },
    { id: 6, eng: "a marker", ru: "маркер", hint: "/ə ˈmɑːkər/" },
    { id: 7, eng: "a cup", ru: "чашка", hint: "/ə kʌp/" },
    { id: 8, eng: "a notebook", ru: "записная книжка, блокнот", hint: "/ə ˈnəʊtbʊk/" },
    { id: 9, eng: "a copybook", ru: "тетрадь", hint: "/ə ˈkɒpibʊk/" },
    { id: 10, eng: "any brush", ru: "любая кисточка", hint: "/ˈɛni brʌʃ/" },
    { id: 11, eng: "a souvenir", ru: "сувенир", hint: "/ə ˌsuːvəˈnɪər/" },
    { id: 12, eng: "a toy", ru: "игрушка", hint: "/ə tɔɪ/" },
    { id: 13, eng: "a key", ru: "ключ", hint: "/ə kiː/" },
    { id: 14, eng: "toilet paper", ru: "туалетная бумага", hint: "/ˈtɔɪlɪt ˈpeɪpər/" },
    { id: 15, eng: "flowers", ru: "цветы", hint: "/ˈflaʊərz/" },
    { id: 16, eng: "a lighter", ru: "зажигалка", hint: "/ə ˈlaɪtər/" },
    { id: 17, eng: "a nail clipper", ru: "ножницы для ногтей", hint: "/ə neɪl ˈklɪpər/" },
    { id: 18, eng: "a guitar", ru: "гитара", hint: "/ə ɡɪˈtɑːr/" },
    { id: 19, eng: "different", ru: "разный", hint: "/ˈdɪfərənt/" },
    { id: 20, eng: "a thing", ru: "вещь", hint: "/ə θɪŋ/" },
    { id: 21, eng: "things", ru: "вещи", hint: "/θɪŋz/" },
    { id: 22, eng: "materials", ru: "материалы", hint: "/məˈtɪəriəlz/" },
    { id: 23, eng: "rubber", ru: "резина", hint: "/ˈrʌbər/" },
    { id: 24, eng: "fabric", ru: "ткань", hint: "/ˈfæbrɪk/" },
    { id: 25, eng: "ceramic", ru: "керамика", hint: "/səˈræmɪk/" },
    { id: 26, eng: "plastic", ru: "пластик", hint: "/ˈplæstɪk/" },
    { id: 27, eng: "metal", ru: "металл", hint: "/ˈmetəl/" },
    { id: 28, eng: "wood", ru: "дерево", hint: "/wʊd/" },
    { id: 29, eng: "paper", ru: "бумага", hint: "/ˈpeɪpər/" },
    { id: 30, eng: "stone", ru: "камень", hint: "/stəʊn/" },
    { id: 31, eng: "clay", ru: "глина", hint: "/kleɪ/" },
    { id: 32, eng: "discount", ru: "скидка", hint: "/ˈdɪskaʊnt/" },
    { id: 33, eng: "shop", ru: "магазин", hint: "/ʃɒp/" },
    { id: 34, eng: "delivery", ru: "доставка", hint: "/dɪˈlɪvəri/" },
    { id: 35, eng: "absolutely", ru: "абсолютно", hint: "/ˈæbsəluːtli/" },
    { id: 36, eng: "free", ru: "бесплатный", hint: "/friː/" },
    { id: 37, eng: "order", ru: "заказ, заказывать", hint: "/ˈɔːdər/" },
    { id: 38, eng: "noname brand", ru: "малоизвестный бренд", hint: "/ˈnəʊneɪm brænd/" },
    { id: 39, eng: "euro", ru: "евро", hint: "/ˈjʊərəʊ/" },
    { id: 40, eng: "rubber band", ru: "резинка", hint: "/ˈrʌbər bænd/" },
    { id: 41, eng: "let me show you", ru: "позвольте показать вам", hint: "/let mi ʃəʊ ju/" }
  ],
  devModeNumbers: [
        { id: 1, eng: "one", ru: "один" },
        { id: 2, eng: "two", ru: "два" },
        { id: 3, eng: "three", ru: "три" },
        { id: 4, eng: "four", ru: "четыре" },
        { id: 5, eng: "five", ru: "пять" },
        { id: 6, eng: "six", ru: "шесть" },
        { id: 7, eng: "seven", ru: "семь" },
        { id: 8, eng: "eight", ru: "восемь" },
        { id: 9, eng: "nine", ru: "девять" },
        { id: 10, eng: "ten", ru: "десять" },
        { id: 11, eng: "eleven", ru: "одиннадцать" },
        { id: 12, eng: "twelve", ru: "двенадцать" },
        { id: 13, eng: "thirteen", ru: "тринадцать" },
        { id: 14, eng: "fourteen", ru: "четырнадцать" },
        { id: 15, eng: "fifteen", ru: "пятнадцать" },
        { id: 16, eng: "sixteen", ru: "шестнадцать" },
        { id: 17, eng: "seventeen", ru: "семнадцать" },
        { id: 18, eng: "eighteen", ru: "восемнадцать" },
        { id: 19, eng: "nineteen", ru: "девятнадцать" },
        { id: 20, eng: "twenty", ru: "двадцать" },
        { id: 21, eng: "first", ru: "первый" },
        { id: 22, eng: "zero", ru: "ноль" },
        { id: 23, eng: "third", ru: "третий" },
        { id: 24, eng: "thirty", ru: "тридцать" },
        { id: 25, eng: "forty", ru: "сорок" },
        { id: 26, eng: "fifty", ru: "пятьдесят" },
        { id: 27, eng: "eighty", ru: "восемьдесят" },
        { id: 28, eng: "ninety", ru: "девяносто" },
        { id: 29, eng: "hundred", ru: "сто" },
        { id: 30, eng: "thousand", ru: "тысяча" },
        { id: 31, eng: "million", ru: "миллион" },
        { id: 32, eng: "billion", ru: "миллиард" },
    ],
    a1words: [
      { id: 3, eng: "about", ru: "о, примерно", Lvl: "A" },
      { id: 4, eng: "above", ru: "над", Lvl: "A" },
      { id: 5, eng: "across the road", ru: "через дорогу", Lvl: "A" },
      { id: 6, eng: "action", ru: "действие", Lvl: "A" },
      { id: 7, eng: "activity", ru: "активность, занятие", Lvl: "A" },
      { id: 8, eng: "actor", ru: "актёр", Lvl: "A" },
      { id: 9, eng: "actress", ru: "актриса", Lvl: "A" },
      { id: 10, eng: "add", ru: "добавлять", Lvl: "A" },
      { id: 11, eng: "address", ru: "адрес", Lvl: "A" },
      { id: 12, eng: "adult", ru: "взрослый", Lvl: "A" },
      { id: 13, eng: "advice", ru: "совет", Lvl: "A" },
      { id: 14, eng: "afraid", ru: "испуганный", Lvl: "A" },
      { id: 15, eng: "after", ru: "после", Lvl: "A" },
      { id: 16, eng: "afternoon", ru: "день (после полудня)", Lvl: "A" },
      { id: 17, eng: "again", ru: "снова", Lvl: "A" },
      { id: 18, eng: "age", ru: "возраст", Lvl: "A" },
      { id: 19, eng: "ago", ru: "назад, спустя время", Lvl: "A" },
      { id: 20, eng: "agree", ru: "соглашаться", Lvl: "A" },
      { id: 21, eng: "air", ru: "воздух", Lvl: "A" },
      { id: 22, eng: "airport", ru: "аэропорт", Lvl: "A" },
      { id: 23, eng: "all", ru: "все", Lvl: "A" },
      { id: 24, eng: "also", ru: "также", Lvl: "A" },
      { id: 25, eng: "always", ru: "всегда", Lvl: "A" },
      { id: 26, eng: "amazing", ru: "удивительный", Lvl: "A" },
      { id: 27, eng: "and", ru: "и", Lvl: "A" },
      { id: 28, eng: "angry", ru: "злой", Lvl: "A" },
      { id: 29, eng: "animal", ru: "животное", Lvl: "A" },
      { id: 30, eng: "another", ru: "другой", Lvl: "A" },
      { id: 31, eng: "answer", ru: "ответ", Lvl: "A" },
      { id: 32, eng: "any", ru: "любой", Lvl: "A" },
      { id: 33, eng: "anyone", ru: "кто-нибудь", Lvl: "A" },
      { id: 34, eng: "anything", ru: "что-нибудь", Lvl: "A" },
      { id: 35, eng: "apartment", ru: "квартира", Lvl: "A" },
      { id: 36, eng: "apple", ru: "яблоко", Lvl: "A" },
      { id: 37, eng: "April", ru: "апрель", Lvl: "A" },
      { id: 38, eng: "area", ru: "область, район", Lvl: "A" },
      { id: 39, eng: "arm", ru: "рука (от кисти до плеча)", Lvl: "A" },
      { id: 40, eng: "around", ru: "вокруг", Lvl: "A" },
      { id: 41, eng: "arrive", ru: "прибывать", Lvl: "A" },
      { id: 42, eng: "art", ru: "искусство", Lvl: "A" },
      { id: 43, eng: "article", ru: "статья", Lvl: "A" },
      { id: 44, eng: "artist", ru: "художник", Lvl: "A" },
      { id: 45, eng: "as", ru: "как, поскольку", Lvl: "A" },
      { id: 46, eng: "ask", ru: "спрашивать", Lvl: "A" },
      { id: 47, eng: "at", ru: "в, на (место)", Lvl: "A" },
      { id: 48, eng: "August", ru: "август", Lvl: "A" },
      { id: 49, eng: "aunt", ru: "тётя", Lvl: "A" },
      { id: 50, eng: "autumn", ru: "осень", Lvl: "A" },
      { id: 51, eng: "away", ru: "прочь, вдали", Lvl: "A" },
      { id: 52, eng: "baby", ru: "ребёнок, малыш", Lvl: "A" },
      { id: 53, eng: "back", ru: "спина, назад", Lvl: "A" },
      { id: 54, eng: "bad", ru: "плохой", Lvl: "A" },
      { id: 55, eng: "bag", ru: "сумка", Lvl: "A" },
      { id: 56, eng: "ball", ru: "мяч", Lvl: "A" },
      { id: 57, eng: "banana", ru: "банан", Lvl: "A" },
      { id: 58, eng: "band", ru: "группа (музыкальная)", Lvl: "A" },
      { id: 59, eng: "bank", ru: "банк", Lvl: "A" },
      { id: 60, eng: "bath", ru: "ванна", Lvl: "A" },
      { id: 61, eng: "bathroom", ru: "ванная комната", Lvl: "A" },
      { id: 62, eng: "be", ru: "быть", Lvl: "A" },
      { id: 63, eng: "beach", ru: "пляж", Lvl: "A" },
      { id: 64, eng: "beautiful", ru: "красивый", Lvl: "A" },
      { id: 65, eng: "because", ru: "потому что", Lvl: "A" },
      { id: 66, eng: "become", ru: "становиться", Lvl: "A" },
      { id: 67, eng: "bed", ru: "кровать", Lvl: "A" },
      { id: 68, eng: "bedroom", ru: "спальня", Lvl: "A" },
      { id: 69, eng: "beer", ru: "пиво", Lvl: "A" },
      { id: 70, eng: "before", ru: "до, перед", Lvl: "A" },
      { id: 71, eng: "begin", ru: "начинать", Lvl: "A" },
      { id: 72, eng: "beginning", ru: "начало", Lvl: "A" },
      { id: 73, eng: "behind", ru: "позади", Lvl: "A" },
      { id: 74, eng: "believe", ru: "верить", Lvl: "A" },
      { id: 75, eng: "below", ru: "ниже", Lvl: "A" },
      { id: 76, eng: "best", ru: "лучший", Lvl: "A" },
      { id: 77, eng: "better", ru: "лучше", Lvl: "A" },
      { id: 78, eng: "between", ru: "между", Lvl: "A" },
      { id: 79, eng: "bicycle", ru: "велосипед", Lvl: "A" },
      { id: 80, eng: "big", ru: "большой", Lvl: "A" },
      { id: 81, eng: "bike", ru: "велосипед", Lvl: "A" },
      { id: 82, eng: "bill", ru: "счёт (в ресторане)", Lvl: "A" },
      { id: 83, eng: "bird", ru: "птица", Lvl: "A" },
      { id: 84, eng: "birthday", ru: "день рождения", Lvl: "A" },
      { id: 85, eng: "black", ru: "чёрный", Lvl: "A" },
      { id: 86, eng: "blog", ru: "блог", Lvl: "A" },
      { id: 87, eng: "blonde", ru: "блондин(ка)", Lvl: "A" },
      { id: 88, eng: "blue", ru: "синий", Lvl: "A" },
      { id: 89, eng: "boat", ru: "лодка", Lvl: "A" },
      { id: 90, eng: "body", ru: "тело", Lvl: "A" },
      { id: 91, eng: "book", ru: "книга", Lvl: "A" },
      { id: 92, eng: "boot", ru: "ботинок", Lvl: "A" },
      { id: 93, eng: "bored", ru: "скучающий", Lvl: "A" },
      { id: 94, eng: "boring", ru: "скучный", Lvl: "A" },
      { id: 95, eng: "born", ru: "рождённый", Lvl: "A" },
      { id: 96, eng: "both", ru: "оба", Lvl: "A" },
      { id: 97, eng: "bottle", ru: "бутылка", Lvl: "A" },
      { id: 98, eng: "box", ru: "коробка", Lvl: "A" },
      { id: 99, eng: "boy", ru: "мальчик", Lvl: "A" },
      { id: 100, eng: "boyfriend", ru: "парень", Lvl: "A" },
      { id: 101, eng: "bread", ru: "хлеб", Lvl: "A" },
      { id: 102, eng: "break", ru: "ломать, перерыв", Lvl: "A" },
      { id: 103, eng: "breakfast", ru: "завтрак", Lvl: "A" },
      { id: 104, eng: "bring", ru: "приносить", Lvl: "A" },
      { id: 105, eng: "brother", ru: "брат", Lvl: "A" },
      { id: 106, eng: "brown", ru: "коричневый", Lvl: "A" },
      { id: 107, eng: "build", ru: "строить", Lvl: "A" },
      { id: 108, eng: "building", ru: "здание", Lvl: "A" },
      { id: 109, eng: "bus", ru: "автобус", Lvl: "A" },
      { id: 110, eng: "business", ru: "бизнес", Lvl: "A" },
      { id: 111, eng: "busy", ru: "занятый", Lvl: "A" },
      { id: 112, eng: "but", ru: "но", Lvl: "A" },
      { id: 113, eng: "butter", ru: "масло", Lvl: "A" },
      { id: 114, eng: "buy", ru: "покупать", Lvl: "A" },
      { id: 115, eng: "by", ru: "к, по, рядом с", Lvl: "A" },
      { id: 116, eng: "bye", ru: "пока", Lvl: "A" },
      { id: 117, eng: "cafe", ru: "кафе", Lvl: "A" },
      { id: 118, eng: "cake", ru: "торт", Lvl: "A" },
      { id: 119, eng: "call", ru: "звонить, называть", Lvl: "A" },
      { id: 120, eng: "camera", ru: "камера", Lvl: "A" },
      { id: 121, eng: "can", ru: "мочь, банка", Lvl: "A" },
      { id: 122, eng: "cannot", ru: "не могу", Lvl: "A" },
      { id: 123, eng: "capital", ru: "столица", Lvl: "A" },
      { id: 124, eng: "car", ru: "машина", Lvl: "A" },
      { id: 125, eng: "card", ru: "карта, открытка", Lvl: "A" },
      { id: 126, eng: "career", ru: "карьера", Lvl: "A" },
      { id: 127, eng: "carrot", ru: "морковь", Lvl: "A" },
      { id: 128, eng: "carry", ru: "нести", Lvl: "A" },
      { id: 129, eng: "cat", ru: "кошка", Lvl: "A" },
      { id: 130, eng: "CD", ru: "компакт-диск", Lvl: "A" },
      { id: 131, eng: "cent", ru: "цент", Lvl: "A" },
      { id: 132, eng: "centre", ru: "центр", Lvl: "A" },
      { id: 133, eng: "century", ru: "век", Lvl: "A" },
      { id: 134, eng: "chair", ru: "стул", Lvl: "A" },
      { id: 135, eng: "change", ru: "менять, сдача", Lvl: "A" },
      { id: 136, eng: "chart", ru: "диаграмма", Lvl: "A" },
      { id: 137, eng: "cheap", ru: "дешёвый", Lvl: "A" },
      { id: 138, eng: "check", ru: "проверять, чек", Lvl: "A" },
      { id: 139, eng: "cheese", ru: "сыр", Lvl: "A" },
      { id: 140, eng: "chicken", ru: "курица", Lvl: "A" },
      { id: 141, eng: "child", ru: "ребёнок", Lvl: "A" },
      { id: 142, eng: "chocolate", ru: "шоколад", Lvl: "A" },
      { id: 143, eng: "choose", ru: "выбирать", Lvl: "A" },
      { id: 144, eng: "cinema", ru: "кинотеатр", Lvl: "A" },
      { id: 145, eng: "city", ru: "город", Lvl: "A" },
      { id: 146, eng: "class", ru: "класс, урок", Lvl: "A" },
      { id: 147, eng: "classroom", ru: "классная комната", Lvl: "A" },
      { id: 148, eng: "clean", ru: "чистый, убирать", Lvl: "A" },
      { id: 149, eng: "climb", ru: "карабкаться", Lvl: "A" },
      { id: 150, eng: "clock", ru: "часы (настенные)", Lvl: "A" },
      { id: 151, eng: "close", ru: "закрывать", Lvl: "A" },
      { id: 152, eng: "clothes", ru: "одежда", Lvl: "A" },
      { id: 153, eng: "club", ru: "клуб", Lvl: "A" },
      { id: 154, eng: "coat", ru: "пальто", Lvl: "A" },
      { id: 155, eng: "coffee", ru: "кофе", Lvl: "A" },
      { id: 156, eng: "cold", ru: "холодный, простуда", Lvl: "A" },
      { id: 157, eng: "college", ru: "колледж", Lvl: "A" },
      { id: 158, eng: "colour", ru: "цвет", Lvl: "A" },
      { id: 159, eng: "come", ru: "приходить", Lvl: "A" },
      { id: 160, eng: "common", ru: "общий", Lvl: "A" },
      { id: 161, eng: "company", ru: "компания", Lvl: "A" },
      { id: 162, eng: "compare", ru: "сравнивать", Lvl: "A" },
      { id: 163, eng: "complete", ru: "завершать, полный", Lvl: "A" },
      { id: 164, eng: "computer", ru: "компьютер", Lvl: "A" },
      { id: 165, eng: "concert", ru: "концерт", Lvl: "A" },
      { id: 166, eng: "conversation", ru: "разговор", Lvl: "A" },
      { id: 167, eng: "cook", ru: "готовить, повар", Lvl: "A" },
      { id: 168, eng: "cooking", ru: "готовка", Lvl: "A" },
      { id: 169, eng: "cool", ru: "крутой, прохладный", Lvl: "A" },
      { id: 170, eng: "correct", ru: "правильный", Lvl: "A" },
      { id: 171, eng: "cost", ru: "стоить, стоимость", Lvl: "A" },
      { id: 172, eng: "could", ru: "мог (прошедшее от can)", Lvl: "A" },
      { id: 173, eng: "country", ru: "страна, сельская местность", Lvl: "A" },
      { id: 174, eng: "course", ru: "курс", Lvl: "A" },
      { id: 175, eng: "cousin", ru: "двоюродный брат/сестра", Lvl: "A" },
      { id: 176, eng: "cow", ru: "корова", Lvl: "A" },
      { id: 177, eng: "cream", ru: "крем", Lvl: "A" },
      { id: 178, eng: "create", ru: "создавать", Lvl: "A" },
      { id: 179, eng: "culture", ru: "культура", Lvl: "A" },
      { id: 180, eng: "cup", ru: "чашка", Lvl: "A" },
      { id: 181, eng: "customer", ru: "клиент", Lvl: "A" },
      { id: 182, eng: "cut", ru: "резать", Lvl: "A" },
      { id: 183, eng: "dad", ru: "папа", Lvl: "A" },
      { id: 184, eng: "dance", ru: "танцевать, танец", Lvl: "A" },
      { id: 185, eng: "dancer", ru: "танцор", Lvl: "A" },
      { id: 186, eng: "dancing", ru: "танцы", Lvl: "A" },
      { id: 187, eng: "dangerous", ru: "опасный", Lvl: "A" },
      { id: 188, eng: "dark", ru: "тёмный", Lvl: "A" },
      { id: 189, eng: "date", ru: "дата, свидание", Lvl: "A" },
      { id: 190, eng: "daughter", ru: "дочь", Lvl: "A" },
      { id: 191, eng: "day", ru: "день", Lvl: "A" },
      { id: 192, eng: "dear", ru: "дорогой", Lvl: "A" },
      { id: 193, eng: "December", ru: "декабрь", Lvl: "A" },
      { id: 194, eng: "decide", ru: "решать", Lvl: "A" },
      { id: 195, eng: "delicious", ru: "вкусный", Lvl: "A" },
      { id: 196, eng: "describe", ru: "описывать", Lvl: "A" },
      { id: 197, eng: "description", ru: "описание", Lvl: "A" },
      { id: 198, eng: "design", ru: "дизайн", Lvl: "A" },
      { id: 199, eng: "desk", ru: "письменный стол", Lvl: "A" },
      { id: 200, eng: "detail", ru: "деталь", Lvl: "A" },
      { id: 201, eng: "dialogue", ru: "диалог", Lvl: "A" },
      { id: 202, eng: "dictionary", ru: "словарь", Lvl: "A" },
      { id: 203, eng: "die", ru: "умирать", Lvl: "A" },
      { id: 204, eng: "diet", ru: "диета", Lvl: "A" },
      { id: 205, eng: "difference", ru: "разница", Lvl: "A" },
      { id: 206, eng: "different", ru: "разный", Lvl: "A" },
      { id: 207, eng: "difficult", ru: "трудный", Lvl: "A" },
      { id: 208, eng: "dinner", ru: "ужин", Lvl: "A" },
      { id: 209, eng: "dirty", ru: "грязный", Lvl: "A" },
      { id: 210, eng: "discuss", ru: "обсуждать", Lvl: "A" },
      { id: 211, eng: "dish", ru: "блюдо, тарелка", Lvl: "A" },
      { id: 212, eng: "do", ru: "делать", Lvl: "A" },
      { id: 213, eng: "doctor", ru: "врач", Lvl: "A" },
      { id: 214, eng: "dog", ru: "собака", Lvl: "A" },
      { id: 215, eng: "dollar", ru: "доллар", Lvl: "A" },
      { id: 216, eng: "door", ru: "дверь", Lvl: "A" },
      { id: 217, eng: "down", ru: "вниз", Lvl: "A" },
      { id: 218, eng: "go downstairs", ru: "спускаться по лестнице", Lvl: "A" },
      { id: 219, eng: "draw", ru: "рисовать", Lvl: "A" },
      { id: 220, eng: "dress", ru: "платье", Lvl: "A" },
      { id: 221, eng: "drink", ru: "пить", Lvl: "A" },
      { id: 222, eng: "drive", ru: "водить", Lvl: "A" },
      { id: 223, eng: "driver", ru: "водитель", Lvl: "A" },
      { id: 224, eng: "during", ru: "в течение", Lvl: "A" },

    ],

  popularIrregularVerbs: [
    { id: 1, eng: "forget", ru: "забывать" },
    { id: 2, eng: "have", ru: "иметь" },
    { id: 3, eng: "do", ru: "делать" },
    { id: 4, eng: "say", ru: "сказать" },
    { id: 5, eng: "go", ru: "идти" },
    { id: 6, eng: "get", ru: "получать" },
    { id: 7, eng: "make", ru: "делать" },
    { id: 8, eng: "know", ru: "знать" },
    { id: 9, eng: "think", ru: "думать" },
    { id: 10, eng: "take", ru: "брать" },
    { id: 11, eng: "see", ru: "видеть" },
    { id: 12, eng: "come", ru: "приходить" },
    { id: 13, eng: "find", ru: "находить" },
    { id: 14, eng: "give", ru: "давать" },
    { id: 15, eng: "tell", ru: "рассказывать" },
    { id: 16, eng: "become", ru: "становиться" },
    { id: 17, eng: "show", ru: "показывать" },
    { id: 18, eng: "leave", ru: "покидать" },
    { id: 19, eng: "feel", ru: "чувствовать" },
    { id: 20, eng: "put", ru: "класть" },
    { id: 21, eng: "bring", ru: "приносить" },
    { id: 22, eng: "begin", ru: "начинать" },
    { id: 23, eng: "keep", ru: "сохранять" },
    { id: 24, eng: "hold", ru: "держать" },
    { id: 25, eng: "write", ru: "писать" },
    { id: 26, eng: "stand", ru: "стоять" },
    { id: 27, eng: "hear", ru: "слышать" },
    { id: 28, eng: "let", ru: "позволять" },
    { id: 29, eng: "forgive", ru: "прощать" },
    { id: 30, eng: "freeze", ru: "замерзать" },
    { id: 31, eng: "meet", ru: "встречать" },
    { id: 32, eng: "run", ru: "бегать" },
    { id: 33, eng: "pay", ru: "платить" },
    { id: 34, eng: "sit", ru: "сидеть" },
    { id: 35, eng: "speak", ru: "говорить" },
    { id: 36, eng: "swear", ru: "материться" },
    { id: 37, eng: "tell a lie", ru: "лгать" },
    { id: 38, eng: "read", ru: "читать" },
    { id: 39, eng: "grow", ru: "расти" },
    { id: 40, eng: "lose", ru: "терять" },
    { id: 41, eng: "fall", ru: "падать" },
    { id: 42, eng: "send", ru: "отправлять" },
    { id: 43, eng: "build", ru: "строить" },
    { id: 44, eng: "understand", ru: "понимать" },
    { id: 45, eng: "draw", ru: "рисовать" },
    { id: 46, eng: "break", ru: "ломать" },
    { id: 47, eng: "spend", ru: "тратить" },
    { id: 48, eng: "cut", ru: "резать" },

    ],
  clothes: [
    // Level A (A1, A2)
    { id: 1, eng: "hat", ru: "шляпа", EnglishLevel: "A" },
    { id: 2, eng: "cap", ru: "кепка", EnglishLevel: "A" },
    { id: 3, eng: "scarf", ru: "шарф", EnglishLevel: "A" },
    { id: 4, eng: "gloves", ru: "перчатки", EnglishLevel: "A" },
    { id: 5, eng: "jacket", ru: "куртка", EnglishLevel: "A" },
    { id: 6, eng: "coat", ru: "пальто", EnglishLevel: "A" },
    { id: 7, eng: "sweater", ru: "свитер", EnglishLevel: "A" },
    { id: 8, eng: "shirt", ru: "рубашка", EnglishLevel: "A" },
    { id: 9, eng: "t-shirt", ru: "футболка", EnglishLevel: "A" },
    { id: 10, eng: "jeans", ru: "джинсы", EnglishLevel: "A" },
    { id: 11, eng: "trousers", ru: "брюки", EnglishLevel: "A" },
    { id: 12, eng: "pants", ru: "штаны (амер.)", EnglishLevel: "A" },
    { id: 13, eng: "shorts", ru: "шорты", EnglishLevel: "A" },
    { id: 14, eng: "skirt", ru: "юбка", EnglishLevel: "A" },
    { id: 15, eng: "dress", ru: "платье", EnglishLevel: "A" },
    { id: 16, eng: "underwear", ru: "нижнее белье", EnglishLevel: "A" },
    { id: 17, eng: "socks", ru: "носки", EnglishLevel: "A" },
    { id: 18, eng: "tights", ru: "колготки", EnglishLevel: "A" },
    { id: 19, eng: "boots", ru: "ботинки", EnglishLevel: "A" },
    { id: 20, eng: "shoes", ru: "туфли", EnglishLevel: "A" },
    { id: 21, eng: "sneakers", ru: "кроссовки", EnglishLevel: "A" },
    { id: 22, eng: "slippers", ru: "тапочки", EnglishLevel: "A" },
    { id: 23, eng: "belt", ru: "ремень", EnglishLevel: "A" },
    { id: 24, eng: "pocket", ru: "карман", EnglishLevel: "A" },
    { id: 25, eng: "buttons", ru: "пуговицы", EnglishLevel: "A" },
    { id: 26, eng: "hood", ru: "капюшон", EnglishLevel: "A" },
    { id: 28, eng: "swimsuit", ru: "купальник", EnglishLevel: "A" },
    { id: 29, eng: "bag", ru: "сумка", EnglishLevel: "A" },
    { id: 31, eng: "backpack", ru: "рюкзак", EnglishLevel: "A" },
    { id: 32, eng: "wallet", ru: "бумажник", EnglishLevel: "A" },
    { id: 33, eng: "umbrella", ru: "зонтик", EnglishLevel: "A" },
    { id: 34, eng: "watch", ru: "наручные часы", EnglishLevel: "A" },
    { id: 35, eng: "ring", ru: "кольцо", EnglishLevel: "A" },
    { id: 36, eng: "glasses", ru: "очки", EnglishLevel: "A" },
    { id: 37, eng: "sunglasses", ru: "солнцезащитные очки", EnglishLevel: "A" },
    { id: 39, eng: "style", ru: "стиль", EnglishLevel: "A" },
    { id: 40, eng: "jewellery", ru: "ювелирные изделия", EnglishLevel: "B" },

    // Level B (B1, B2)
    { id: 41, eng: "hoodie", ru: "толстовка с капюшоном", EnglishLevel: "B" },
    { id: 42, eng: "jumper", ru: "джемпер", EnglishLevel: "B" },
    { id: 45, eng: "suit", ru: "костюм", EnglishLevel: "B" },
    { id: 46, eng: "tie", ru: "галстук", EnglishLevel: "B" },
    { id: 47, eng: "bow tie", ru: "бабочка", EnglishLevel: "B" },
    { id: 48, eng: "tank top", ru: "майка", EnglishLevel: "B" },
    { id: 49, eng: "blouse", ru: "блузка", EnglishLevel: "B" },
    { id: 50, eng: "leggings", ru: "леггинсы", EnglishLevel: "B" },
    { id: 52, eng: "overalls", ru: "комбинезон", EnglishLevel: "B" },
    { id: 53, eng: "bra", ru: "бюстгальтер", EnglishLevel: "B" },
    { id: 54, eng: "panties", ru: "трусики", EnglishLevel: "B" },
    { id: 56, eng: "stockings", ru: "чулки", EnglishLevel: "B" },
    { id: 57, eng: "sandals", ru: "сандалии", EnglishLevel: "B" },
    { id: 58, eng: "flip-flops", ru: "шлепанцы", EnglishLevel: "B" },
    { id: 59, eng: "heels", ru: "туфли на каблуке", EnglishLevel: "B" },
    { id: 60, eng: "zipper", ru: "молния", EnglishLevel: "B" },
    { id: 61, eng: "laces", ru: "шнурки", EnglishLevel: "B" },
    { id: 62, eng: "collar", ru: "воротник", EnglishLevel: "B" },
    { id: 64, eng: "rain coat", ru: "дождевик", EnglishLevel: "B" },
    { id: 65, eng: "vest", ru: "жилет", EnglishLevel: "B" },
    { id: 68, eng: "outfit", ru: "наряд", EnglishLevel: "B" },

    { id: 72, eng: "earrings", ru: "серьги", EnglishLevel: "B" },
    { id: 73, eng: "necklace", ru: "ожерелье", EnglishLevel: "B" },
    { id: 74, eng: "bracelet", ru: "браслет", EnglishLevel: "B" },
    { id: 75, eng: "purse", ru: "кошелек (брит.)", EnglishLevel: "B" },
    { id: 76, eng: "helmet", ru: "шлем", EnglishLevel: "B" },
    { id: 78, eng: "robe", ru: "халат", EnglishLevel: "B" },

    // Level C (C1, C+)
    { id: 81, eng: "attire", ru: "облачение", EnglishLevel: "C" },
    { id: 83, eng: "windbreaker", ru: "ветровка", EnglishLevel: "C" },
    { id: 84, eng: "cloak", ru: "плащ", EnglishLevel: "C" },
    { id: 88, eng: "gown", ru: "халат/мантия", EnglishLevel: "C" },
    { id: 89, eng: "veil", ru: "вуаль/фата", EnglishLevel: "C" },
    { id: 91, eng: "tuxedo", ru: "смокинг", EnglishLevel: "C" },
    { id: 92, eng: "cape", ru: "накидка", EnglishLevel: "C" },
    ],

  randomSet: [

    // Вопросительные слова
    { id: 1, eng: "What", ru: "что" },
    { id: 2, eng: "Where", ru: "где" },
    { id: 3, eng: "Why", ru: "почему" },

    // Внешность (Appearance)
    { id: 4, eng: "beautiful", ru: "красивая" },
    { id: 5, eng: "handsome", ru: "красивый" },
    { id: 6, eng: "tall", ru: "высокий" },
    { id: 7, eng: "short", ru: "низкий" },
    { id: 8, eng: "curly hair", ru: "кудрявые волосы" },

    // Части тела (Parts of the Body)
    { id: 9, eng: "head", ru: "голова" },
    { id: 10, eng: "nose", ru: "нос" },
    { id: 11, eng: "eyes", ru: "глаза" },
    { id: 12, eng: "fingers", ru: "пальцы" },

    // Характер (Character)
    { id: 13, eng: "kind", ru: "добрый" },
    { id: 14, eng: "unkind", ru: "злой" },
    { id: 15, eng: "angry", ru: "сердитый" },
    { id: 16, eng: "happy", ru: "счастливый" },
    { id: 17, eng: "sad", ru: "грустный" },
    { id: 18, eng: "clever", ru: "умный" },
    { id: 19, eng: "silly", ru: "глупый" },
    { id: 20, eng: "polite", ru: "вежливый" },
    { id: 21, eng: "shy", ru: "стеснительный" },
    { id: 22, eng: "calm", ru: "спокойный" },
    { id: 23, eng: "friendly", ru: "дружелюбный" },
    { id: 24, eng: "strong", ru: "сильный" },
    { id: 25, eng: "weak", ru: "слабый" },

    // Дополнительные популярные слова
    { id: 26, eng: "brave", ru: "храбрый" },
    { id: 27, eng: "honest", ru: "честный" },
    { id: 28, eng: "funny", ru: "смешной" },
    { id: 29, eng: "serious", ru: "серьёзный" },
    { id: 30, eng: "creative", ru: "креативный" },
    { id: 31, eng: "patient", ru: "терпеливый" },

    // Профессии (Jobs)
    { id: 32, eng: "driver", ru: "водитель" },
    { id: 33, eng: "doctor", ru: "врач" },
    { id: 34, eng: "teacher", ru: "учитель" },

    // Действия (Actions)
    { id: 35, eng: "smile", ru: "улыбаться" },
    { id: 36, eng: "run", ru: "бегать" },
    { id: 37, eng: "swim", ru: "плавать" },

    // Фразы для общенияm
    { id: 38, eng: "Hello!", ru: "Привет!" },
    { id: 39, eng: "Thank you!", ru: "Спасибо!" },
    { id: 40, eng: "Goodbye!", ru: "Пока!" },
    { id: 41, eng: "how long", ru: "как долго", hint: "/ хау лонг /" },
    { id: 42, eng: "when", ru: "когда", hint: "/ уэн /" },
    { id: 43, eng: "how often", ru: "как часто", hint: "" },
    { id: 44, eng: "who", ru: "кто", hint: "" },


  ],
  explain: [
    // Местоимения
    { id: 1, eng: "I", ru: "я", hint: "/ ай /" },
    { id: 2, eng: "You", ru: "мы", hint: "/ ю /" },
    { id: 3, eng: "We", ru: "ты", hint: "/ ви /" },
    { id: 4, eng: "They", ru: "вы", hint: "/ дэй /" },
    { id: 5, eng: "He", ru: "он", hint: "/ хи /" },
    { id: 6, eng: "She", ru: "она", hint: "/ щи /" },
    { id: 7, eng: "It", ru: "оно", hint: "/ ит /" },

    // Предлоги местоположения
    { id: 8, eng: "in", ru: "в", hint: "/ ин /" },
    { id: 9, eng: "on", ru: "на", hint: "/ он /" },
    { id: 10, eng: "under", ru: "под", hint: "/ андэр /" },
    { id: 11, eng: "next to, by, near", ru: "рядом с, возле, у", hint: "/ некст ту /" },
    { id: 12, eng: "behind", ru: "позади", hint: "/ бихайнд /" },
    { id: 13, eng: "in front of", ru: "перед", hint: "/ ин фронт ов /" },
    { id: 14, eng: "between", ru: "между", hint: "/ битуин /" },
    { id: 15, eng: "above", ru: "над", hint: "/ эба́в /" },
    { id: 16, eng: "among us", ru: "среди нас", hint: "/ эмо́н /" },

    // Цвета
    { id: 17, eng: "red", ru: "красный", hint: "/ ред /" },
    { id: 18, eng: "blue", ru: "синий", hint: "/ блу /" },
    { id: 19, eng: "green", ru: "зелёный", hint: "/ грин /" },
    { id: 20, eng: "yellow", ru: "жёлтый", hint: "/ йелоу /" },
    { id: 21, eng: "black", ru: "чёрный", hint: "/ блэк /" },
    { id: 22, eng: "white", ru: "белый", hint: "/ уайт /" },
    { id: 23, eng: "brown", ru: "коричневый", hint: "/ браун /" },
    { id: 24, eng: "orange", ru: "оранжевый", hint: "/ ориндж /" },
    { id: 25, eng: "pink", ru: "розовый", hint: "/ пинк /" },
    { id: 26, eng: "gray", ru: "серый", hint: "/ грэй /" },

    // Животные
    { id: 27, eng: "cat", ru: "кот", hint: "/ кэт /" },
    { id: 28, eng: "dog", ru: "собака", hint: "/ дог /" },
    { id: 29, eng: "cow", ru: "корова", hint: "/ кау /" },
    { id: 30, eng: "duck", ru: "утка", hint: "/ дак /" },
    { id: 31, eng: "pig", ru: "свинья", hint: "/ пиг /" },
    { id: 32, eng: "horse", ru: "лошадь", hint: "/ хoрс /" },
    { id: 33, eng: "fish", ru: "рыба", hint: "/ фиш /" },
    { id: 34, eng: "bird", ru: "птица", hint: "/ бёрд /" },
    { id: 35, eng: "rabbit", ru: "кролик", hint: "/ рэбит /" },
    { id: 36, eng: "bear", ru: "медведь", hint: "/ бэа /" },

    // Транспорт
    { id: 37, eng: "car", ru: "машина", hint: "/ кар /" },
    { id: 38, eng: "bus", ru: "автобус", hint: "/ бас /" },
    { id: 39, eng: "bike", ru: "велосипед", hint: "/ байк /" },
    { id: 40, eng: "train", ru: "поезд", hint: "/ трейн /" },
    { id: 41, eng: "plane", ru: "самолёт", hint: "/ плейн /" },
    { id: 42, eng: "ship", ru: "корабль", hint: "/ шип /" },
    { id: 43, eng: "truck", ru: "грузовик", hint: "/ трак /" },

    // Профессии (дополнение)
    { id: 44, eng: "cook", ru: "повар", hint: "/ кук /" },
    { id: 45, eng: "doctor", ru: "врач", hint: "/ доктэ /" },
    { id: 46, eng: "killer", ru: "убийца", hint: "/ кИллер /" },
    { id: 47, eng: "teacher", ru: "учитель", hint: "/ тичэ /" },
    { id: 48, eng: "farmer", ru: "фермер", hint: "/ фармэ /" },
    { id: 49, eng: "driver", ru: "водитель", hint: "/ драйвэ /" },
    { id: 50, eng: "builder", ru: "строитель", hint: "/ билдэ /" },
    { id: 51, eng: "fireman", ru: "пожарный", hint: "/ файамэн /" },
    { id: 52, eng: "police", ru: "полиция", hint: "/ полИс /" },
    { id: 53, eng: "sailor", ru: "моряк", hint: "/ атист /" },

    { id: 54, eng: "pineapple", ru: "ананас", hint: "/ пайн эпл /" },
    { id: 55, eng: "banana", ru: "банан", hint: "/ бэ'нана /" },
    { id: 56, eng: "carrot", ru: "морковь", hint: "/ кэрэт /" },
    { id: 57, eng: "bread", ru: "хлеб", hint: "/ бред /" },
    { id: 58, eng: "milk", ru: "молоко", hint: "/ милк /" },
    { id: 59, eng: "cheese", ru: "сыр", hint: "/ чиз /" },
    { id: 60, eng: "eggs", ru: "яйца", hint: "/ эгз /" },
    { id: 61, eng: "cucumber", ru: "огурец", hint: "/ кьЮкамбэ /" },


    { id: 62, eng: "book", ru: "книга", hint: "/ бук /" },
    { id: 63, eng: "pen", ru: "ручка", hint: "/ пэн /" },
    { id: 64, eng: "pencil", ru: "карандаш", hint: "/ пэнсил /" },
    { id: 65, eng: "bag", ru: "сумка", hint: "/ бэг /" },
    { id: 66, eng: "ruler", ru: "линейка", hint: "/ рулэ /" },
    { id: 67, eng: "eraser", ru: "ластик", hint: "/ ирэйзэ /" },
    { id: 68, eng: "notebook", ru: "тетрадь", hint: "/ ноутбук /" },
    { id: 69, eng: "desk", ru: "парта", hint: "/ деск /" },
    { id: 70, eng: "chair", ru: "стул", hint: "/ чэа /" },

  ],

}
export default questionsData
