// чтобы удалить пустые строки нужно ввести в CTRL+F или CTRL R
// ^\s*$\n
const questionsData = {

    devModeNumbers: [
        { id: 1, eng: "one", ru: "один" },
        { id: 2, eng: "two", ru: "два" },
        { id: 3, eng: "three", ru: "три" },
        { id: 4, eng: "four", ru: "четыре" },
        { id: 5, eng: "five", ru: "пять" },
        { id: 6, eng: "six", ru: "шесть" },
        { id: 7, eng: "seven", ru: "семь" },
        { id: 8, eng: "eight", ru: "восемь" },
        { id: 9, eng: "nine", ru: "девять" },
        { id: 10, eng: "ten", ru: "десять" },
        { id: 11, eng: "eleven", ru: "одиннадцать" },
        { id: 12, eng: "twelve", ru: "двенадцать" },
        { id: 13, eng: "thirteen", ru: "тринадцать" },
        { id: 14, eng: "fourteen", ru: "четырнадцать" },
        { id: 15, eng: "fifteen", ru: "пятнадцать" },
        { id: 16, eng: "sixteen", ru: "шестнадцать" },
        { id: 17, eng: "seventeen", ru: "семнадцать" },
        { id: 18, eng: "eighteen", ru: "восемнадцать" },
        { id: 19, eng: "nineteen", ru: "девятнадцать" },
        { id: 20, eng: "twenty", ru: "двадцать" },
        { id: 21, eng: "first", ru: "первый" },
        { id: 22, eng: "zero", ru: "ноль" },
        { id: 23, eng: "third", ru: "третий" },
        { id: 24, eng: "thirty", ru: "тридцать" },
        { id: 25, eng: "forty", ru: "сорок" },
        { id: 26, eng: "fifty", ru: "пятьдесят" },
        { id: 27, eng: "eighty", ru: "восемьдесят" },
        { id: 28, eng: "ninety", ru: "девяносто" },
        { id: 29, eng: "hundred", ru: "сто" },
        { id: 30, eng: "thousand", ru: "тысяча" },
        { id: 31, eng: "million", ru: "миллион" },
        { id: 32, eng: "billion", ru: "миллиард" },
    ],
  popularIrregularVerbs: [
    { id: 1, eng: "forget", ru: "забывать" },
    { id: 2, eng: "have", ru: "иметь" },
    { id: 3, eng: "do", ru: "делать" },
    { id: 4, eng: "say", ru: "сказать" },
    { id: 5, eng: "go", ru: "идти" },
    { id: 6, eng: "get", ru: "получать" },
    { id: 7, eng: "make", ru: "делать" },
    { id: 8, eng: "know", ru: "знать" },
    { id: 9, eng: "think", ru: "думать" },
    { id: 10, eng: "take", ru: "брать" },
    { id: 11, eng: "see", ru: "видеть" },
    { id: 12, eng: "come", ru: "приходить" },
    { id: 13, eng: "find", ru: "находить" },
    { id: 14, eng: "give", ru: "давать" },
    { id: 15, eng: "tell", ru: "рассказывать" },
    { id: 16, eng: "become", ru: "становиться" },
    { id: 17, eng: "show", ru: "показывать" },
    { id: 18, eng: "leave", ru: "покидать" },
    { id: 19, eng: "feel", ru: "чувствовать" },
    { id: 20, eng: "put", ru: "класть" },
    { id: 21, eng: "bring", ru: "приносить" },
    { id: 22, eng: "begin", ru: "начинать" },
    { id: 23, eng: "keep", ru: "сохранять" },
    { id: 24, eng: "hold", ru: "держать" },
    { id: 25, eng: "write", ru: "писать" },
    { id: 26, eng: "stand", ru: "стоять" },
    { id: 27, eng: "hear", ru: "слышать" },
    { id: 28, eng: "let", ru: "позволять" },
    { id: 29, eng: "forgive", ru: "прощать" },
    { id: 30, eng: "freeze", ru: "замерзать" },
    { id: 31, eng: "meet", ru: "встречать" },
    { id: 32, eng: "run", ru: "бегать" },
    { id: 33, eng: "pay", ru: "платить" },
    { id: 34, eng: "sit", ru: "сидеть" },
    { id: 35, eng: "speak", ru: "говорить" },
    { id: 36, eng: "swear", ru: "материться" },
    { id: 37, eng: "tell a lie", ru: "лгать" },
    { id: 38, eng: "read", ru: "читать" },
    { id: 39, eng: "grow", ru: "расти" },
    { id: 40, eng: "lose", ru: "терять" },
    { id: 41, eng: "fall", ru: "падать" },
    { id: 42, eng: "send", ru: "отправлять" },
    { id: 43, eng: "build", ru: "строить" },
    { id: 44, eng: "understand", ru: "понимать" },
    { id: 45, eng: "draw", ru: "рисовать" },
    { id: 46, eng: "break", ru: "ломать" },
    { id: 47, eng: "spend", ru: "тратить" },
    { id: 48, eng: "cut", ru: "резать" },

    ],
  clothes: [
    // Level A (A1, A2)
    { id: 1, eng: "hat", ru: "шляпа", EnglishLevel: "A" },
    { id: 2, eng: "cap", ru: "кепка", EnglishLevel: "A" },
    { id: 3, eng: "scarf", ru: "шарф", EnglishLevel: "A" },
    { id: 4, eng: "gloves", ru: "перчатки", EnglishLevel: "A" },
    { id: 5, eng: "jacket", ru: "куртка", EnglishLevel: "A" },
    { id: 6, eng: "coat", ru: "пальто", EnglishLevel: "A" },
    { id: 7, eng: "sweater", ru: "свитер", EnglishLevel: "A" },
    { id: 8, eng: "shirt", ru: "рубашка", EnglishLevel: "A" },
    { id: 9, eng: "t-shirt", ru: "футболка", EnglishLevel: "A" },
    { id: 10, eng: "jeans", ru: "джинсы", EnglishLevel: "A" },
    { id: 11, eng: "trousers", ru: "брюки", EnglishLevel: "A" },
    { id: 12, eng: "pants", ru: "штаны (амер.)", EnglishLevel: "A" },
    { id: 13, eng: "shorts", ru: "шорты", EnglishLevel: "A" },
    { id: 14, eng: "skirt", ru: "юбка", EnglishLevel: "A" },
    { id: 15, eng: "dress", ru: "платье", EnglishLevel: "A" },
    { id: 16, eng: "underwear", ru: "нижнее белье", EnglishLevel: "A" },
    { id: 17, eng: "socks", ru: "носки", EnglishLevel: "A" },
    { id: 18, eng: "tights", ru: "колготки", EnglishLevel: "A" },
    { id: 19, eng: "boots", ru: "ботинки", EnglishLevel: "A" },
    { id: 20, eng: "shoes", ru: "туфли", EnglishLevel: "A" },
    { id: 21, eng: "sneakers", ru: "кроссовки", EnglishLevel: "A" },
    { id: 22, eng: "slippers", ru: "тапочки", EnglishLevel: "A" },
    { id: 23, eng: "belt", ru: "ремень", EnglishLevel: "A" },
    { id: 24, eng: "pocket", ru: "карман", EnglishLevel: "A" },
    { id: 25, eng: "buttons", ru: "пуговицы", EnglishLevel: "A" },
    { id: 26, eng: "hood", ru: "капюшон", EnglishLevel: "A" },
    { id: 28, eng: "swimsuit", ru: "купальник", EnglishLevel: "A" },
    { id: 29, eng: "bag", ru: "сумка", EnglishLevel: "A" },
    { id: 31, eng: "backpack", ru: "рюкзак", EnglishLevel: "A" },
    { id: 32, eng: "wallet", ru: "бумажник", EnglishLevel: "A" },
    { id: 33, eng: "umbrella", ru: "зонтик", EnglishLevel: "A" },
    { id: 34, eng: "watch", ru: "наручные часы", EnglishLevel: "A" },
    { id: 35, eng: "ring", ru: "кольцо", EnglishLevel: "A" },
    { id: 36, eng: "glasses", ru: "очки", EnglishLevel: "A" },
    { id: 37, eng: "sunglasses", ru: "солнцезащитные очки", EnglishLevel: "A" },
    { id: 39, eng: "style", ru: "стиль", EnglishLevel: "A" },
    { id: 40, eng: "jewellery", ru: "ювелирные изделия", EnglishLevel: "B" },

    // Level B (B1, B2)
    { id: 41, eng: "hoodie", ru: "толстовка с капюшоном", EnglishLevel: "B" },
    { id: 42, eng: "jumper", ru: "джемпер", EnglishLevel: "B" },
    { id: 45, eng: "suit", ru: "костюм", EnglishLevel: "B" },
    { id: 46, eng: "tie", ru: "галстук", EnglishLevel: "B" },
    { id: 47, eng: "bow tie", ru: "бабочка", EnglishLevel: "B" },
    { id: 48, eng: "tank top", ru: "майка", EnglishLevel: "B" },
    { id: 49, eng: "blouse", ru: "блузка", EnglishLevel: "B" },
    { id: 50, eng: "leggings", ru: "леггинсы", EnglishLevel: "B" },
    { id: 52, eng: "overalls", ru: "комбинезон", EnglishLevel: "B" },
    { id: 53, eng: "bra", ru: "бюстгальтер", EnglishLevel: "B" },
    { id: 54, eng: "panties", ru: "трусики", EnglishLevel: "B" },
    { id: 56, eng: "stockings", ru: "чулки", EnglishLevel: "B" },
    { id: 57, eng: "sandals", ru: "сандалии", EnglishLevel: "B" },
    { id: 58, eng: "flip-flops", ru: "шлепанцы", EnglishLevel: "B" },
    { id: 59, eng: "heels", ru: "туфли на каблуке", EnglishLevel: "B" },
    { id: 60, eng: "zipper", ru: "молния", EnglishLevel: "B" },
    { id: 61, eng: "laces", ru: "шнурки", EnglishLevel: "B" },
    { id: 62, eng: "collar", ru: "воротник", EnglishLevel: "B" },
    { id: 64, eng: "rain coat", ru: "дождевик", EnglishLevel: "B" },
    { id: 65, eng: "vest", ru: "жилет", EnglishLevel: "B" },
    { id: 68, eng: "outfit", ru: "наряд", EnglishLevel: "B" },

    { id: 72, eng: "earrings", ru: "серьги", EnglishLevel: "B" },
    { id: 73, eng: "necklace", ru: "ожерелье", EnglishLevel: "B" },
    { id: 74, eng: "bracelet", ru: "браслет", EnglishLevel: "B" },
    { id: 75, eng: "purse", ru: "кошелек (брит.)", EnglishLevel: "B" },
    { id: 76, eng: "helmet", ru: "шлем", EnglishLevel: "B" },
    { id: 78, eng: "robe", ru: "халат", EnglishLevel: "B" },

    // Level C (C1, C+)
    { id: 81, eng: "attire", ru: "облачение", EnglishLevel: "C" },
    { id: 83, eng: "windbreaker", ru: "ветровка", EnglishLevel: "C" },
    { id: 84, eng: "cloak", ru: "плащ", EnglishLevel: "C" },
    { id: 88, eng: "gown", ru: "халат/мантия", EnglishLevel: "C" },
    { id: 89, eng: "veil", ru: "вуаль/фата", EnglishLevel: "C" },
    { id: 91, eng: "tuxedo", ru: "смокинг", EnglishLevel: "C" },
    { id: 92, eng: "cape", ru: "накидка", EnglishLevel: "C" },
    ],

  randomSet: [

    // Вопросительные слова
    { id: 1, eng: "What", ru: "что" },
    { id: 2, eng: "Where", ru: "где" },
    { id: 3, eng: "Why", ru: "почему" },

    // Внешность (Appearance)
    { id: 4, eng: "beautiful", ru: "красивая" },
    { id: 5, eng: "handsome", ru: "красивый" },
    { id: 6, eng: "tall", ru: "высокий" },
    { id: 7, eng: "short", ru: "низкий" },
    { id: 8, eng: "curly hair", ru: "кудрявые волосы" },

    // Части тела (Parts of the Body)
    { id: 9, eng: "head", ru: "голова" },
    { id: 10, eng: "nose", ru: "нос" },
    { id: 11, eng: "eyes", ru: "глаза" },
    { id: 12, eng: "fingers", ru: "пальцы" },

    // Характер (Character)
    { id: 13, eng: "kind", ru: "добрый" },
    { id: 14, eng: "unkind", ru: "злой" },
    { id: 15, eng: "angry", ru: "сердитый" },
    { id: 16, eng: "happy", ru: "счастливый" },
    { id: 17, eng: "sad", ru: "грустный" },
    { id: 18, eng: "clever", ru: "умный" },
    { id: 19, eng: "silly", ru: "глупый" },
    { id: 20, eng: "polite", ru: "вежливый" },
    { id: 21, eng: "shy", ru: "стеснительный" },
    { id: 22, eng: "calm", ru: "спокойный" },
    { id: 23, eng: "friendly", ru: "дружелюбный" },
    { id: 24, eng: "strong", ru: "сильный" },
    { id: 25, eng: "weak", ru: "слабый" },

    // Дополнительные популярные слова
    { id: 26, eng: "brave", ru: "храбрый" },
    { id: 27, eng: "honest", ru: "честный" },
    { id: 28, eng: "funny", ru: "смешной" },
    { id: 29, eng: "serious", ru: "серьёзный" },
    { id: 30, eng: "creative", ru: "креативный" },
    { id: 31, eng: "patient", ru: "терпеливый" },

    // Профессии (Jobs)
    { id: 32, eng: "driver", ru: "водитель" },
    { id: 33, eng: "doctor", ru: "врач" },
    { id: 34, eng: "teacher", ru: "учитель" },

    // Действия (Actions)
    { id: 35, eng: "smile", ru: "улыбаться" },
    { id: 36, eng: "run", ru: "бегать" },
    { id: 37, eng: "swim", ru: "плавать" },

    // Фразы для общения
    { id: 38, eng: "Hello!", ru: "Привет!" },
    { id: 39, eng: "Thank you!", ru: "Спасибо!" },
    { id: 40, eng: "Goodbye!", ru: "Пока!" },
    { id: 41, eng: "how long", ru: "как долго", hint: "/ хау лонг /" },
    { id: 42, eng: "when", ru: "когда", hint: "/ уэн /" },
    { id: 43, eng: "how often", ru: "как часто", hint: "" },
    { id: 44, eng: "who", ru: "кто", hint: "" },


  ],
  explain: [
    // Местоимения
    { id: 1, eng: "I", ru: "я", hint: "/ ай /" },
    { id: 2, eng: "You", ru: "мы", hint: "/ ю /" },
    { id: 3, eng: "We", ru: "ты", hint: "/ ви /" },
    { id: 4, eng: "They", ru: "вы", hint: "/ дэй /" },
    { id: 5, eng: "He", ru: "он", hint: "/ хи /" },
    { id: 6, eng: "She", ru: "она", hint: "/ щи /" },
    { id: 7, eng: "It", ru: "оно", hint: "/ ит /" },

    // Предлоги местоположения
    { id: 8, eng: "in", ru: "в", hint: "/ ин /" },
    { id: 9, eng: "on", ru: "на", hint: "/ он /" },
    { id: 10, eng: "under", ru: "под", hint: "/ андэр /" },
    { id: 11, eng: "next to, by, near", ru: "рядом с, возле, у", hint: "/ некст ту /" },
    { id: 12, eng: "behind", ru: "позади", hint: "/ бихайнд /" },
    { id: 13, eng: "in front of", ru: "перед", hint: "/ ин фронт ов /" },
    { id: 14, eng: "between", ru: "между", hint: "/ битуин /" },
    { id: 15, eng: "above", ru: "над", hint: "/ эба́в /" },
    { id: 16, eng: "among us", ru: "среди нас", hint: "/ эмо́н /" },

    // Цвета
    { id: 17, eng: "red", ru: "красный", hint: "/ ред /" },
    { id: 18, eng: "blue", ru: "синий", hint: "/ блу /" },
    { id: 19, eng: "green", ru: "зелёный", hint: "/ грин /" },
    { id: 20, eng: "yellow", ru: "жёлтый", hint: "/ йелоу /" },
    { id: 21, eng: "black", ru: "чёрный", hint: "/ блэк /" },
    { id: 22, eng: "white", ru: "белый", hint: "/ уайт /" },
    { id: 23, eng: "brown", ru: "коричневый", hint: "/ браун /" },
    { id: 24, eng: "orange", ru: "оранжевый", hint: "/ ориндж /" },
    { id: 25, eng: "pink", ru: "розовый", hint: "/ пинк /" },
    { id: 26, eng: "gray", ru: "серый", hint: "/ грэй /" },

    // Животные
    { id: 27, eng: "cat", ru: "кот", hint: "/ кэт /" },
    { id: 28, eng: "dog", ru: "собака", hint: "/ дог /" },
    { id: 29, eng: "cow", ru: "корова", hint: "/ кау /" },
    { id: 30, eng: "duck", ru: "утка", hint: "/ дак /" },
    { id: 31, eng: "pig", ru: "свинья", hint: "/ пиг /" },
    { id: 32, eng: "horse", ru: "лошадь", hint: "/ хoрс /" },
    { id: 33, eng: "fish", ru: "рыба", hint: "/ фиш /" },
    { id: 34, eng: "bird", ru: "птица", hint: "/ бёрд /" },
    { id: 35, eng: "rabbit", ru: "кролик", hint: "/ рэбит /" },
    { id: 36, eng: "bear", ru: "медведь", hint: "/ бэа /" },

    // Транспорт
    { id: 37, eng: "car", ru: "машина", hint: "/ кар /" },
    { id: 38, eng: "bus", ru: "автобус", hint: "/ бас /" },
    { id: 39, eng: "bike", ru: "велосипед", hint: "/ байк /" },
    { id: 40, eng: "train", ru: "поезд", hint: "/ трейн /" },
    { id: 41, eng: "plane", ru: "самолёт", hint: "/ плейн /" },
    { id: 42, eng: "ship", ru: "корабль", hint: "/ шип /" },
    { id: 43, eng: "truck", ru: "грузовик", hint: "/ трак /" },

    // Профессии (дополнение)
    { id: 44, eng: "cook", ru: "повар", hint: "/ кук /" },
    { id: 45, eng: "doctor", ru: "врач", hint: "/ доктэ /" },
    { id: 46, eng: "killer", ru: "убийца", hint: "/ кИллер /" },
    { id: 47, eng: "teacher", ru: "учитель", hint: "/ тичэ /" },
    { id: 48, eng: "farmer", ru: "фермер", hint: "/ фармэ /" },
    { id: 49, eng: "driver", ru: "водитель", hint: "/ драйвэ /" },
    { id: 50, eng: "builder", ru: "строитель", hint: "/ билдэ /" },
    { id: 51, eng: "fireman", ru: "пожарный", hint: "/ файамэн /" },
    { id: 52, eng: "police", ru: "полиция", hint: "/ полИс /" },
    { id: 53, eng: "sailor", ru: "моряк", hint: "/ атист /" },

    { id: 54, eng: "pineapple", ru: "ананас", hint: "/ пайн эпл /" },
    { id: 55, eng: "banana", ru: "банан", hint: "/ бэ'нана /" },
    { id: 56, eng: "carrot", ru: "морковь", hint: "/ кэрэт /" },
    { id: 57, eng: "bread", ru: "хлеб", hint: "/ бред /" },
    { id: 58, eng: "milk", ru: "молоко", hint: "/ милк /" },
    { id: 59, eng: "cheese", ru: "сыр", hint: "/ чиз /" },
    { id: 60, eng: "eggs", ru: "яйца", hint: "/ эгз /" },
    { id: 61, eng: "cucumber", ru: "огурец", hint: "/ кьЮкамбэ /" },


    { id: 62, eng: "book", ru: "книга", hint: "/ бук /" },
    { id: 63, eng: "pen", ru: "ручка", hint: "/ пэн /" },
    { id: 64, eng: "pencil", ru: "карандаш", hint: "/ пэнсил /" },
    { id: 65, eng: "bag", ru: "сумка", hint: "/ бэг /" },
    { id: 66, eng: "ruler", ru: "линейка", hint: "/ рулэ /" },
    { id: 67, eng: "eraser", ru: "ластик", hint: "/ ирэйзэ /" },
    { id: 68, eng: "notebook", ru: "тетрадь", hint: "/ ноутбук /" },
    { id: 69, eng: "desk", ru: "парта", hint: "/ деск /" },
    { id: 70, eng: "chair", ru: "стул", hint: "/ чэа /" },

  ],

}
export default questionsData
